name:                watson
version:             0.1.0.0
github:              "drellem/watson"
license:             BSD3
author:              "Daniel Miller"
maintainer:          "gate46dmiller@gmail.com"
copyright:           "Daniel Miller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/watson#readme>

dependencies:
- base >= 4.7 && < 5
- text
- array
- lens
- pqueue
- heap
- QuickCheck
- aeson

library:
  source-dirs: src

executables:
  watson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - watson

tests:
  watson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - watson
